name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Format
        run: terraform fmt -check -recursive

      - name: Init (no backend, no credentials)
        working-directory: envs/lab
        run: terraform init -backend=false -input=false

      - name: Validate
        working-directory: envs/lab
        run: terraform validate

      - name: Test (mocked AWS provider)
        working-directory: envs/lab
        run: terraform test

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          version: v1.28.14
          github_token: ${{ github.token }} # avoids GitHub API rate limits when the action downloads tfsec
